export const brand = {
  name: "Krishna IPTV",
  tagline: "#1 Indian IPTV Service in USA & Canada",
  phone: "+1 361 494 0799",
  whatsapp: "13614940799",
  email: "support@krishnaiptv.com",
  colors: {
    primary: "#FFD700",
    primaryDark: "#FFA500",
    bg: "#08080f",
    bgCard: "#0f0f1a",
    bgCard2: "#13131f",
    border: "rgba(255,215,0,0.15)",
    text: "#f0f0ff",
    muted: "#8888aa",
  },
  plans: [
    {
      name: "3-Month Plan",
      tag: "Short-Term Flexibility",
      duration: "3 Months",
      price: "$33",
      perMonth: "$11/mo",
      popular: false,
      badge: null,
      icon: "📺",
      color: "#4f8ef7",
      devices: 1,
      quality: "HD & 4K",
    },
    {
      name: "6-Month Plan",
      tag: "Best Mid-Term Deal",
      duration: "6 Months",
      price: "$60",
      perMonth: "$10/mo",
      popular: false,
      badge: null,
      icon: "🎬",
      color: "#6c63ff",
      devices: 1,
      quality: "HD & 4K",
    },
    {
      name: "1-Year Plan",
      tag: "Best Annual Deal",
      duration: "1 Year",
      price: "$115",
      perMonth: "$10/mo",
      popular: true,
      badge: "Most Popular",
      icon: "⭐",
      color: "#FFD700",
      devices: 2,
      quality: "Ultra HD 4K",
    },
    {
      name: "2-Year Plan",
      tag: "Ultimate Long-Term Value",
      duration: "2 Years",
      price: "$210",
      perMonth: "$9/mo",
      popular: false,
      badge: "Best Value",
      icon: "💎",
      color: "#e879f9",
      devices: 3,
      quality: "Ultra HD 4K",
    },
    {
      name: "3-Year Plan",
      tag: "Maximum Savings",
      duration: "3 Years",
      price: "$270",
      perMonth: "$7.5/mo",
      popular: false,
      badge: "Super Saver",
      icon: "🏆",
      color: "#4ade80",
      devices: 3,
      quality: "Ultra HD 4K",
    },
    {
      name: "5-Year Plan",
      tag: "Ultimate Value Forever",
      duration: "5 Years",
      price: "$340",
      perMonth: "$5.7/mo",
      popular: false,
      badge: "Best Deal Ever",
      icon: "👑",
      color: "#fb923c",
      devices: 4,
      quality: "Ultra HD 4K",
    },
    {
      name: "Free Trial",
      tag: "Try Before You Buy",
      duration: "Trial",
      price: "$0",
      perMonth: "FREE",
      popular: false,
      badge: "🎁 Free",
      icon: "🎁",
      color: "#4ade80",
      devices: 1,
      quality: "HD",
    },
  ],
  features: [
    "Access to 8000+ live Indian and international channels",
    "230+ Hindi TV channels included",
    "Full language coverage: Hindi, Punjabi, Tamil, Telugu, Malayalam, Kannada, Bengali, Gujarati, Marathi, Odia, Urdu, Nepali & more",
    "Pause & rewind feature for live channels",
    "Catch-up TV: Rewind HD channels for up to 7 days",
    "Huge Indian movie selection",
    "Ultra HD 4K streaming for crystal-clear quality",
    "Works on Smart TVs, Android Boxes, Firestick & more",
    "24/7 customer support from our dedicated team",
  ],
  channels: {
    total: "8,000+",
    vod: "100,000+",
    languages: ["Hindi", "Punjabi", "Urdu", "Tamil", "Telugu", "Malayalam", "Gujarati", "Bengali", "Kannada", "Marathi", "Odia", "Nepali", "English"],
  },
};
